### ISSUE TITLE
Impossible to download from webtoon

### ISSUE THREAD

**Issue by stanthewizzard** [potatoeggy/mandown#60]
[1] 59059
zsh: no matches found: https://www.webtoons.com/en/challenge/test/1-1/viewer?title_no=XXXXXX&episode_no=YYYY

[1]  + exit 1     mandown get 

thanks for help

**Comment by potatoeggy** [comment]
Try adding quotes around the url?

**Comment by stanthewizzard** [comment]
Thanks
In this case I have this error message

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/mandown", line 8, in <module>
    sys.exit(main())

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/cli.py", line 524, in main
    app()

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/cli.py", line 385, in get
    comic = cli_query(url)

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/cli.py", line 146, in cli_query
    comic = api.query(url)

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/api.py", line 33, in query
    return BaseComic(adapter.metadata, adapter.chapters)

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/sources/base_source.py", line 27, in metadata
    self._metadata = self.fetch_metadata()

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mandown/sources/source_webtoons.py", line 45, in fetch_metadata
    art_start_idx = cover_art_el["style"].find("url(") + len("url(")

TypeError: 'NoneType' object is not subscriptable

**Comment by potatoeggy** [comment]
Thanks for the update! https://www.webtoons.com/en/challenge/test/1-1/viewer?title_no=XXXXXX&episode_no=YYYY doesn't seem like a valid Webtoons.com URL. Is there a specific link you're using that's breaking?

**Comment by stanthewizzard** [comment]
It's the url I'm getting from webtoon

For ex this one
https://www.webtoons.com/en/thriller/grasp/episode-1/viewer?title_no=2854&episode_no=1

**Comment by magicalsoup** [comment]
Which is sthe url you're trying to get working?

It you are referring to [https://www.webtoons.com/en/challenge/test/1-1/viewer?title_no=XXXXXX&episode_no=YYYY](https://www.webtoons.com/en/challenge/test/1-1/viewer?title_no=XXXXXX&episode_no=YYYY), it is not a valid webtoon url so the service will not work.

**Comment by potatoeggy** [comment]
@stanthewizzard 

> https://www.webtoons.com/en/thriller/grasp/episode-1/viewer?title_no=2854&episode_no=1

I can't reproduce the error with this link. Do you have another one that breaks mandown?

**Comment by stanthewizzard** [comment]
awesome thanks

**Comment by potatoeggy** [comment]
:tada:
