### ISSUE TITLE
[BUG] Does not work at all on latest Arch Linux

### ISSUE THREAD

**Issue by neuroarter** [potatoeggy/mandown#61]
**What broke?**

- [ ] Downloader
- [ ] Processor
- [x] Converter
- [ ] Other

**Describe the bug**
Does not work at all.

**Steps to reproduce**
Just install it on latest Arch Linux update by using
`pip3 install mandown`
and then try to convert some cbz into epub using this command:
`mandown convert epub manga.ch1.cbz`
you will get this output instead of manga.ch1.epub:
```
Converting to epub...
Pre-converting comic  [------------------------------------]    0%
Traceback (most recent call last):

File "/home/me/.local/bin/mandown", line 8, in <module>
sys.exit(main())

File "/home/me/.local/lib/python3.10/site-packages/mandown/cli.py", line 524, in main
app()

File "/home/me/.local/lib/python3.10/site-packages/mandown/cli.py", line 256, in convert
cli_convert(folder_path, convert_to, dest, remove_after)

File "/home/me/.local/lib/python3.10/site-packages/mandown/cli.py", line 179, in cli_convert
for res in progress:

File "/home/me/.local/lib/python3.10/site-packages/mandown/api.py", line 153, in convert_progress
yield from comicon.convert_progress(

File "/home/me/.local/lib/python3.10/site-packages/comicon/api.py", line 21, in convert_progress
yield from create_cir_progress(first, tempdir)

File "/home/me/.local/lib/python3.10/site-packages/comicon/inputs/__init__.py", line 64, in create_cir_progress
yield from INPUT_FN_MAP[ext or inferred_ext](path, dest)

File "/home/me/.local/lib/python3.10/site-packages/comicon/inputs/cbz.py", line 121, in create_cir
yield str(filename)

UnboundLocalError: local variable 'filename' referenced before assignment
```

**Additional context**
host info:x86_64

**Comment by potatoeggy** [comment]
Thank you for your bug report! It should be fixed now. Give the new version (1.3.4) a try?
